bookafy/bookafy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('accounts/', include('accounts.passwords.urls')),
    
    path('', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('newsfeeds.urls')),
    path('', include('friends.urls')),
    path('messages/', include('communications.urls')), 
    path('timeline/', include('userprofiles.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookafy/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

bookafy/friends/urls.py
from django.urls import path
from .views import *

app_name = "friends"

urlpatterns = [
    path('find-friends', FindFriendsListView.as_view(), name="find-friends"),
    path('friend-requests', FriendRequestsListView.as_view(), name="friend-requests"),
    path('send-request/<slug:username>', send_request, name="send-request"),
    path('accept-request/<slug:friend>', accept_request, name="accept-request"),
    path('cancel-request/<slug:friend>', cancel_request, name="cancel-request"),
]

bookafy/friends/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models import Q

from friends.exceptions import AlreadyFriendsError, AlreadyExistsError
from friends.signals import friendship_request_created, friendship_removed, friendship_request_viewed, \
    friendship_request_canceled, friendship_request_accepted

from accounts.models import User


class NotificationManager(models.Manager):

    def user_unread_notification_count(self, user) -> int:
        if not user:
            return 0
        return self.filter(is_read=False, recipient=user).count()


class FriendshipManager(models.Manager):
    """ Friendship manager """

    def friends(self, user):
        """ Return a list of all friends """
        qs = (
            Friend.objects.select_related("from_user", "to_user")
                .filter(to_user=user)
                .all()
        )
        friends = [u.from_user for u in qs]

        return friends

    def requests(self, user):
        """ Return a list of friendship requests """
        qs = (
            FriendshipRequest.objects.select_related("from_user", "to_user")
                .filter(to_user=user)
                .all()
        )
        requests = list(qs)

        return requests

    def sent_requests(self, user):
        """ Return a list of friendship requests from user """
        qs = (
            FriendshipRequest.objects.select_related("from_user", "to_user")
                .filter(from_user=user)
                .all()
        )
        requests = list(qs)

        return requests

    def got_friend_requests(self, user):
        """ Return a list of friendship requests user got """
        qs = (
            FriendshipRequest.objects.select_related("from_user__profile", "to_user")
                .filter(to_user=user)
                .all()
        )
        unread_requests = list(qs)
        return unread_requests

    def unread_requests(self, user):
        """ Return a list of unread friendship requests """
        qs = (
            FriendshipRequest.objects.select_related("from_user", "to_user")
                .filter(to_user=user, viewed__isnull=True)
                .all()
        )
        unread_requests = list(qs)

        return unread_requests

    def unread_request_count(self, user):
        """ Return a count of unread friendship requests """
        count = FriendshipRequest.objects.select_related("from_user", "to_user").filter(to_user=user,
                                                                                        viewed__isnull=True).count()
        return count

    def read_requests(self, user):
        """ Return a list of read friendship requests """
        qs = (
            FriendshipRequest.objects.select_related("from_user", "to_user")
                .filter(to_user=user, viewed__isnull=False)
                .all()
        )
        read_requests = list(qs)

        return read_requests

    def rejected_requests(self, user):
        """ Return a list of rejected friendship requests """
        qs = (
            FriendshipRequest.objects.select_related("from_user", "to_user")
                .filter(to_user=user, rejected__isnull=False)
                .all()
        )
        rejected_requests = list(qs)

        return rejected_requests

    def unrejected_requests(self, user):
        """ All requests that haven't been rejected """
        qs = (
            FriendshipRequest.objects.select_related("from_user", "to_user")
                .filter(to_user=user, rejected__isnull=True)
                .all()
        )
        unrejected_requests = list(qs)

        return unrejected_requests

    def unrejected_request_count(self, user):
        """ Return a count of unrejected friendship requests """
        count = FriendshipRequest.objects.select_related("from_user", "to_user").filter(to_user=user,
                                                                                        rejected__isnull=True).count()
        return count

    def add_friend(self, from_user, to_user, message=None):
        """ Create a friendship request """
        if from_user == to_user:
            raise ValidationError("Users cannot be friends with themselves")

        if self.are_friends(from_user, to_user):
            raise AlreadyFriendsError("Users are already friends")

        if FriendshipRequest.objects.filter(from_user=from_user, to_user=to_user).exists():
            raise AlreadyExistsError("You already requested friendship from this user.")

        if FriendshipRequest.objects.filter(from_user=to_user, to_user=from_user).exists():
            raise AlreadyExistsError("This user already requested friendship from you.")

        if message is None:
            message = ""

        request, created = FriendshipRequest.objects.get_or_create(
            from_user=from_user, to_user=to_user
        )

        if created is False:
            raise AlreadyExistsError("Friendship already requested")

        if message:
            request.message = message
            request.save()

        friendship_request_created.send(sender=request)

        return request

    def remove_friend(self, from_user, to_user):
        """ Destroy a friendship relationship """
        try:
            qs = Friend.objects.filter(
                Q(to_user=to_user, from_user=from_user) | Q(to_user=from_user, from_user=to_user))
            distinct_qs = qs.distinct().all()

            if distinct_qs:
                friendship_removed.send(
                    sender=distinct_qs[0], from_user=from_user, to_user=to_user
                )
                qs.delete()
                return True
            else:
                return False
        except Friend.DoesNotExist:
            return False

    def are_friends(self, user1, user2):
        """ Are these two users friends? """
        try:
            Friend.objects.get(to_user=user1, from_user=user2)
            return True
        except Friend.DoesNotExist:
            return False


class FriendshipRequest(models.Model):
    """ Model to represent friendship requests """

    from_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="friendship_requests_sent",
    )
    to_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="friendship_requests_received",
    )

    message = models.TextField(_("Message"), blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    rejected = models.DateTimeField(blank=True, null=True)
    viewed = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = _("Friendship Request")
        verbose_name_plural = _("Friendship Requests")
        unique_together = ("from_user", "to_user")

    def __str__(self):
        return f"User #{self.from_user_id} friendship requested #{self.to_user_id}"

    def accept(self):
        """ Accept this friendship request """
        Friend.objects.create(from_user=self.from_user, to_user=self.to_user)
        Friend.objects.create(from_user=self.to_user, to_user=self.from_user)
        friendship_request_accepted.send(
            sender=self, from_user=self.from_user, to_user=self.to_user
        )

        self.delete()

        # Delete any reverse requests
        FriendshipRequest.objects.filter(
            from_user=self.to_user, to_user=self.from_user
        ).delete()

        return True

    def reject(self):
        """ reject this friendship request """
        self.rejected = timezone.now()
        self.save()
        return True

    def cancel(self):
        """ cancel this friendship request """
        self.delete()
        friendship_request_canceled.send(sender=self)
        return True

    def mark_viewed(self):
        self.viewed = timezone.now()
        friendship_request_viewed.send(sender=self)
        self.save()
        return True


class Friend(models.Model):
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friends')
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    objects = FriendshipManager()

    class Meta:
        verbose_name = _("Friend")
        verbose_name_plural = _("Friends")
        unique_together = ("from_user", "to_user")

    def __str__(self):
        return f"User #{self.to_user_id} is friends with #{self.from_user_id}"

    def save(self, *args, **kwargs):
        # Ensure users can't be friends with themselves
        if self.to_user == self.from_user:
            raise ValidationError("Users cannot be friends with themselves.")
        super().save(*args, **kwargs)


class CustomNotification(models.Model):
    type = models.CharField(default='friend', max_length=30)
    recipient = models.ForeignKey(
        User,
        related_name='notifications',
        on_delete=models.CASCADE
    )
    is_read = models.BooleanField(default=False, blank=False, db_index=True)
    actor = models.ForeignKey(
        User,
        blank=False,
        on_delete=models.CASCADE
    )
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    obj = GenericForeignKey('content_type', 'object_id')
    url = models.TextField(blank=True, null=True)
    verb = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    deleted = models.BooleanField(default=False, db_index=True)
    emailed = models.BooleanField(default=False, db_index=True)

bookafy/friends/views.py
from rest_framework.decorators import api_view
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import User
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.http import JsonResponse
from django.views.generic import ListView
from django.db.models import Q

from core.contants.common import FRIEND_REQUEST_VERB
from .serializers import NotificationSerializer, FriendshipRequestSerializer
from .models import FriendshipRequest, Friend, CustomNotification


class FindFriendsListView(LoginRequiredMixin, ListView):
    model = Friend
    context_object_name = 'users'
    template_name = "friends/find-friends.html"

    def get_queryset(self):
        current_user_friends = self.request.user.friends.values('id')
        sent_request = list(
            FriendshipRequest.objects.filter(Q(from_user=self.request.user))
            .exclude(to_user_id=self.request.user.id)
            .values_list('to_user_id', flat=True))
        users = User.objects.exclude(id__in=current_user_friends).exclude(id__in=sent_request).exclude(
            id=self.request.user.id)
        return users


class FriendRequestsListView(LoginRequiredMixin, ListView):
    """
    Get all friend requests current user got
    """
    model = Friend
    context_object_name = 'friend_requests'
    template_name = "friends/friend-requests.html"

    def get_queryset(self):
        return Friend.objects.got_friend_requests(user=self.request.user)


def send_request(request, username=None):
    if username is not None:
        friend_user = User.objects.get(username=username)
        try:
            friend_request = Friend.objects.add_friend(request.user, friend_user, message='Hi! I would like to add you')
        except Exception as e:
            data = {
                'status': False,
                'message': str(e),
            }
            return JsonResponse(data)
        channel_layer = get_channel_layer()
        channel = "all_friend_requests_{}".format(friend_user.username)
        async_to_sync(channel_layer.group_send)(
            channel, {
                "type": "notify",  # method name
                "command": "new_friend_request",
                "notification": FriendshipRequestSerializer(friend_request).data
            }
        )
        data = {
            'status': True,
            'message': "Request sent.",
        }
        return JsonResponse(data)
    else:
        pass


def accept_request(request, friend=None):
    if friend is not None:
        friend_user = User.objects.get(username=friend)
        friend_request = FriendshipRequest.objects.get(to_user=request.user, from_user=friend_user)
        friend_request.accept()
        # CustomNotification.objects.filter(recipient=current_user, actor=friend_user).delete()
        data = {
            'status': True,
            'message': "You accepted friend request",
        }
        return JsonResponse(data)


@api_view(['DELETE'])
def cancel_request(request, friend=None):
    if friend is not None:
        friend_user = User.objects.get(username=friend)
        friend_request = FriendshipRequest.objects.get(to_user=request.user, from_user=friend_user)
        friend_request.cancel()
        data = {
            'status': True,
            'message': "Your friend request is removed",
        }
        return JsonResponse(data)

bookafy/templates/friends/find-friends.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col col-xl-12 order-xl-2 col-lg-9 order-lg-2 col-md-12 order-md-1 col-sm-12 col-12">
                <div class="ui-block">
                    <div class="ui-block-title">
                        <h6 class="title">Add Friend</h6>
                        <a href="#" class="more">
                            <svg class="olymp-three-dots-icon">
                                <use xlink:href="svg-icons/sprites/icons.svg#olymp-three-dots-icon"></use>
                            </svg>
                        </a>
                    </div>
                    <!-- Notification List Frien Requests -->
                    <ul class="notification-list friend-requests">
                        {% for user in users %}
                            <li>
                                <div class="author-thumb">
                                    {% if user.profile.profile_image.url %}
                                        <img src="{{ user.profile.profile_image.url }}" class="author-img" alt="author" style="height: 45px">
                                    {% else %}
                                        <img src="{% static 'img/bg-birthdays.jpg' %}" class="author-img" alt="author" style="height: 45px">
                                    {% endif %}
                                </div>
                                <div class="notification-event">
                                    <a href="#" class="h6 notification-friend">{{ user.get_full_name }}</a>
{#                                    <span class="chat-message-item">Mutual Friend: Sarah Hetfield</span>#}
                                </div>
                                <span class="notification-icon">
                                    <a href="javascript:void(0)" data-url="{% url 'friends:send-request' user.username %}" class="add-butn add-friend accept-request" data-ripple="" data-friend="{{ user.username }}">
                                        Send Friend Request
                                    </a>
                                </span>
                            </li>
                        {% endfor %}
                    </ul>
                    <!-- ... end Notification List Friend Requests -->
                </div>
            </div>
        </div>
    </div>

{% endblock %}

bookafy/templates/friends/friend-requests.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% csrf_token %}

    <div class="container">
        <div class="row">
            <div class="col col-xl-12 order-xl-2 col-lg-9 order-lg-2 col-md-12 order-md-1 col-sm-12 col-12">
                <div class="ui-block">
                    <div class="ui-block-title">
                        <h6 class="title">Received Friend Requests</h6>
                    </div>
                    <!-- Notification List Frien Requests -->
                    <ul class="notification-list friend-requests">
                        {% for friend_request in friend_requests %}
                            <li>
                                <div class="author-thumb">
                                    {% if friend_request.from_user.profile.profile_image.url %}
                                        <img src="{{ friend_request.from_user.profile.profile_image.url }}"
                                             class="author-img" alt="author" style="height: 45px">
                                    {% else %}
                                        <img src="{% static 'img/bg-birthdays.jpg' %}" class="author-img" alt="author" style="height: 45px">
                                    {% endif %}
                                </div>
                                <div class="notification-event">
                                    <a href="#"
                                       class="h6 notification-friend">{{ friend_request.from_user.get_full_name }}</a>
                                </div>
                                <span class="notification-icon">
                                    <a href="javascript:void(0)"
                                       onclick="accept(this)"
                                       data-url="{% url 'friends:accept-request' friend_request.from_user.username %}"
                                       class="btn btn-success" data-ripple=""
                                       data-friend="{{ friend_request.from_user.username }}">
                                        Accept Request
                                    </a>
                                    <a href="javascript:void(0)"
                                       data-url="{% url 'friends:accept-request' friend_request.from_user.username %}"
                                       class="btn btn-danger" data-ripple=""
                                       data-friend="{{ friend_request.from_user.username }}">
                                        Reject Request
                                    </a>
                                </span>
                            </li>
                        {% empty %}
                            <li>No requests found.</li>
                        {% endfor %}
                    </ul>
                    <!-- ... end Notification List Friend Requests -->
                </div>
            </div>
        </div>
    </div>

{% endblock %}